### ISSUE TITLE
想考早大

### ISSUE THREAD

**Issue by jasminelong** [Yuuki-Sora/cloud-parody-project#1]
前辈可以给个联系方式吗我也想考这个研究室，想跟你咨询下可以吗

**Comment by Yuuki-Sora** [comment]
Cheers! 

可能的话，不妨考虑一下在推特上私信我。
推特账号在GitHub主页上挂着。

如果有兴趣的话也欢迎来我的主页看看：https://1st.moe/
没有其他问题的话就close issue了。

以上
